[[https://hr.wikipedia.org/wiki/Heideggerovska_terminologija][https://hr.wikipedia.org/wiki/Heideggerovska_terminologija]]

* Kviz o Heideggerovskoj terminologiji
  QUIZ 
Kviz o Heideggerovskoj terminologiji 



"Biti-prema-smrti odnosi se na proces rasta kroz svijet gdje određeno predviđanje vodi Dasein ka stjecanju autentične perspektive." Koji stihovi to najbolje opisuju?

Gle malu voćku poslije kiše:
Puna je kapi pa ih njiše.
I bliješti suncem obasjana,
Čudesna raskoš njenih grana.
Al nek se sunce malko skrije,
Nestane sve te čarolije.
Ona je opet kao prvo,
Obično, jadno, malo drvo.

Ala mi je to divota
Kad se ko okupa!
Što se ne bi kupali,
Voda nije skupa.
Moramo se kupati,
Prljavštinu stresti,
Nečistoća privlači
Rdju i bolesti.
Zato je majka spremila
Vodu, ali mlaku,
Zato je okupala
Svoga malog Laku.
A sad veli "Cicu mi
Pustati ne smete,
Jer će mislit da je sir,
Poješće mi dete."

!Ah, nije život ljudski drugo,
Neg smućeno jedno more,
Neg plav jedna, koju dugo
Biju vali kao gore:
I sred ovih netom tmina
Čoek se rodi, mrijet počina.
Bježi, kud znaš, što hoć’, čini,
Zapad i istok vas obhodi,
I beskrajnoj po pučini
Svijet kružeći Indije brodi;
Krij se u jame gorskijeh hridi:
Smrt svuda te slidom slidi.


Dva od Heideggerovskih najosnovnijih neologizama, "prisutno pri ruci" i "spremno u šaci", koriste se za opisivanje različitih stavova prema stvarima u svijetu. Koja poslovica najbolje opisuje ova dva pojma?

Svaka ptica svome jatu leti.

!Bolje vrabac u ruci nego golub na grani.

S kim si, takav si.


Pojam "Biti-sa" odnosi se na ontološku karakteristiku ljudskog bića, da je ono oduvijek već s drugima svoje vrste. Koja poslovica to najbolje opisuje?

Bez alata nema zanata.

Bolje vrabac u ruci nego golub na grani.

!S kim si, takav si.


Das Zeug odnosi se na predmet u svijetu s kojim imamo smislene poslove. Koja poslovica to najbolje opisuje?

!Bez alata nema zanata.

Svaka ptica svome jatu leti.

S kim si, takav si.
