Kviz o ovoj stranici Wikipedije:

[[https://hr.wikipedia.org/wiki/Heideggerovska_terminologija][https://hr.wikipedia.org/wiki/Heideggerovska_terminologija]]

Kviz možete pokrenuti na sljedeći način:

[[http://wikiquiz.w71.eu/?raw.githubusercontent.com/kresimir71/quiz/main/wikiquiz/Heideggerovska_terminologija.org][http://wikiquiz.w71.eu/?raw.githubusercontent.com/kresimir71/quiz/main/wikiquiz/Heideggerovska_terminologija.org]]

Kviz treba napisati na sljedeći način. U prvom retku poglavlja napišite riječ QUIZ. U sljedeći red upišite naziv kviza i njegov opis. Zatim slijede tri prazna retka. Zatim napišite prvo pitanje nakon čega slijedi prazan red. Odgovori zatim dolaze odvojeni praznim redom. Sljedeće pitanje je od prvog odvojeno s dva prazna retka i tako dalje. Točan odgovor označava se uskličnikom na početku retka:

https://raw.githubusercontent.com/kresimir71/quiz/main/wikiquiz/Heideggerovska_terminologija.org

Ovaj sustav za kvizove koristi "org" oznake:

https://orgmode.org/manual/index.html

* Kviz o Heideggerovskoj terminologiji
  QUIZ 
Kviz o Heideggerovskoj terminologiji 



"Biti-prema-smrti odnosi se na proces rasta kroz svijet gdje određeno predviđanje vodi Dasein ka stjecanju autentične perspektive." Koji stihovi to najbolje opisuju?

Gle malu voćku poslije kiše:
Puna je kapi pa ih njiše.
I bliješti suncem obasjana,
Čudesna raskoš njenih grana.
Al nek se sunce malko skrije,
Nestane sve te čarolije.
Ona je opet kao prvo,
Obično, jadno, malo drvo.

Ala mi je to divota
Kad se ko okupa!
Što se ne bi kupali,
Voda nije skupa.
Moramo se kupati,
Prljavštinu stresti,
Nečistoća privlači
Rdju i bolesti.
Zato je majka spremila
Vodu, ali mlaku,
Zato je okupala
Svoga malog Laku.
A sad veli "Cicu mi
Pustati ne smete,
Jer će mislit da je sir,
Poješće mi dete."

!Ah, nije život ljudski drugo,
Neg smućeno jedno more,
Neg plav jedna, koju dugo
Biju vali kao gore:
I sred ovih netom tmina
Čoek se rodi, mrijet počina.
Bježi, kud znaš, što hoć’, čini,
Zapad i istok vas obhodi,
I beskrajnoj po pučini
Svijet kružeći Indije brodi;
Krij se u jame gorskijeh hridi:
Smrt svuda te slidom slidi.


Dva od Heideggerovskih najosnovnijih neologizama, "prisutno pri ruci" i "spremno u šaci", koriste se za opisivanje različitih stavova prema stvarima u svijetu. Koja poslovica najbolje opisuje ova dva pojma?

Svaka ptica svome jatu leti.

!Bolje vrabac u ruci nego golub na grani.

S kim si, takav si.


Pojam "Biti-sa" odnosi se na ontološku karakteristiku ljudskog bića, da je ono oduvijek već s drugima svoje vrste. Koja poslovica to najbolje opisuje?

Bez alata nema zanata.

Bolje vrabac u ruci nego golub na grani.

!S kim si, takav si.


Das Zeug odnosi se na predmet u svijetu s kojim imamo smislene poslove. Koja poslovica to najbolje opisuje?

!Bez alata nema zanata.

Svaka ptica svome jatu leti.

S kim si, takav si.


Temeljna osnova bivanja-u-svijetu nije, za Heideggera, materija ili duh, nego briga: imati posla s nečim, proizvoditi nešto, baviti se nečim i paziti na to, koristiti se nečim, odreći se nečega i pustiti to, poduzeti, ostvariti, dokazati, ispitivati, smatrati, raspravljati, utvrđivati... Koji citat to najbolje opisuje? 

"Stav je izbor. Sreća je izbor. Optimizam je izbor. Ljubaznost je izbor. Davanje je izbor. Poštovanje je izbor. Koji god izbor napravili, čini vas. Biraj mudro." - Roy T. Bennett

!"Snaga ne dolazi iz pobjede. Vaše borbe razvijaju vaše snage. Kad prolazite kroz teškoće i odlučite se ne predati, to je snaga." - Arnold Schwarzenegger

"Strategija bez taktike najsporiji je put do pobjede. Taktika bez strategije je buka prije poraza." - Sun Tzu


U Heideggerovom gledištu, čovjek definira svoje vlastito biće svojim djelovanjem i izborima, te je sposoban birati među mogućnostima, aktualizirajući barem jednu od raspoloživih mogućnosti dok pritom zatvara druge. Koji citat to najbolje opisuje? 

!"Stav je izbor. Sreća je izbor. Optimizam je izbor. Ljubaznost je izbor. Davanje je izbor. Poštovanje je izbor. Koji god izbor napravili, čini vas. Biraj mudro." - Roy T. Bennett

"Snaga ne dolazi iz pobjede. Vaše borbe razvijaju vaše snage. Kad prolazite kroz teškoće i odlučite se ne predati, to je snaga." - Arnold Schwarzenegger

"Strategija bez taktike najsporiji je put do pobjede. Taktika bez strategije je buka prije poraza." - Sun Tzu
